# Generated by Django 4.2.11 on 2024-04-30 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=11, null=True)),
                ("date_of_birth", models.DateField(max_length=11, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=11
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("Nigeria", "Nigeria"),
                            ("ghana", "ghana"),
                            ("united kingdom", "UK"),
                            ("USA", "USA"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Abia", "Abia"),
                            ("Oyo", "Oyo"),
                            ("Osun", "Osun"),
                            ("Kano", "Kano"),
                            ("Abuja", "Abuja"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "means_of_identity",
                    models.ImageField(null=True, upload_to="identityImage/"),
                ),
                (
                    "particulars",
                    models.FileField(null=True, upload_to="particularsImage/"),
                ),
                (
                    "profile_passport",
                    models.ImageField(null=True, upload_to="profileImage/"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("chairman", "chairman"),
                            ("director", "director"),
                            ("supervisor", "supervisor"),
                            ("admin", "admin"),
                            ("delivery agent", "delivery agent"),
                            ("store keeper", "store keeper"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "single"),
                            ("married", "married"),
                            ("divorce", "divorce"),
                            ("complicated", "complicated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("staff", models.BooleanField(default=False)),
                ("next_of_kin", models.CharField(max_length=20, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
