# Generated by Django 4.2.11 on 2024-04-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female")],
                max_length=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("single", "single"),
                    ("married", "married"),
                    ("divorce", "divorce"),
                    ("complicated", "complicated"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
